/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{ts,tsx,jsx,js}"],
  presets: [require("@treasure-project/tailwind-config")],
  theme: {
    extend: {
      typography: ({ theme }) => ({
        night: {
          css: {
            "--tw-prose-body": theme("colors.night[800]"),
            "--tw-prose-headings": theme("colors.night[900]"),
            "--tw-prose-lead": theme("colors.night[700]"),
            "--tw-prose-links": theme("colors.night[900]"),
            "--tw-prose-bold": theme("colors.night[900]"),
            "--tw-prose-counters": theme("colors.night[600]"),
            "--tw-prose-bullets": theme("colors.night[400]"),
            "--tw-prose-hr": theme("colors.night[300]"),
            "--tw-prose-quotes": theme("colors.night[900]"),
            "--tw-prose-quote-borders": theme("colors.night[300]"),
            "--tw-prose-captions": theme("colors.night[700]"),
            "--tw-prose-code": theme("colors.night[900]"),
            "--tw-prose-pre-code": theme("colors.night[100]"),
            "--tw-prose-pre-bg": theme("colors.night[900]"),
            "--tw-prose-th-borders": theme("colors.night[300]"),
            "--tw-prose-td-borders": theme("colors.night[200]"),
            "--tw-prose-invert-body": theme("colors.night[200]"),
            "--tw-prose-invert-headings": theme("colors.white"),
            "--tw-prose-invert-lead": theme("colors.night[300]"),
            "--tw-prose-invert-links": theme("colors.white"),
            "--tw-prose-invert-bold": theme("colors.white"),
            "--tw-prose-invert-counters": theme("colors.night[400]"),
            "--tw-prose-invert-bullets": theme("colors.night[600]"),
            "--tw-prose-invert-hr": theme("colors.night[700]"),
            "--tw-prose-invert-quotes": theme("colors.night[100]"),
            "--tw-prose-invert-quote-borders": theme("colors.night[700]"),
            "--tw-prose-invert-captions": theme("colors.night[400]"),
            "--tw-prose-invert-code": theme("colors.white"),
            "--tw-prose-invert-pre-code": theme("colors.night[300]"),
            "--tw-prose-invert-pre-bg": "rgb(0 0 0 / 50%)",
            "--tw-prose-invert-th-borders": theme("colors.night[600]"),
            "--tw-prose-invert-td-borders": theme("colors.night[700]"),
          },
        },
      }),
    },
  },
  plugins: [require("tailwindcss-animate"), require("@tailwindcss/typography")],
};
